---
title: "Calculate assortativity for interested institution and specialty subset"
author: "Zeyu Hu"
date: "2024-07-24"
output: html_document
---

```{r setup, include=FALSE}
library(igraph)
library(dplyr)
library(wdnet)
source("/Users/huzeyu/Desktop/network analysis/repo/network-analysis/code/utility.R")
```

## Read the data and select the top 5 institutions and specialties
```{r echo=FALSE}
edges <- read.csv("/Users/huzeyu/Desktop/network analysis/raw data/Edges_Weighted.csv")
nodes <- read.csv("/Users/huzeyu/Desktop/network analysis/raw data/Nodes.csv")
# Calculate the top 5 most frequent institutions
top_institutions <- nodes %>%
  count(Institution, sort = TRUE) %>%
  top_n(5, n)

# Calculate the top 5 most frequent specialties
top_specialties <- nodes %>%
  count(Specialty, sort = TRUE) %>%
  top_n(5, n)

# Print results
cat("Top 5 Institutions:\n", paste(top_institutions$Institution, top_institutions$n, sep = ":", collapse = "\n"), "\n")
cat("Top 5 Specialties:\n", paste(top_specialties$Specialty, top_specialties$n, sep = ": ", collapse = "\n"), "\n")
```
## Calculate the assortativity for interested institution subsets
```{r echo=FALSE}
# Define the institutions of interest
institutions_of_interest <- c(
  "Icahn School of Medicine at Mount Sinai/New York Eye and Ear Infirmary at Mount Sinai",
  "Vanderbilt University Medical Center",
  "Montefiore Medical Center/Albert Einstein College of Medicine",
  "University of Michigan Health System",
  "University of Southern California/LAC+USC Medical Center"
)

# Calculate assortativity for each institution of interest
for (institution in institutions_of_interest) {
  calculate_assortativity_for_institution(institution)
}
```

## Calculate the assortativity for interested specialty subsets
```{r echo=FALSE}
# Define the specialties of interest
specialties_of_interest <- c("Head & Neck", "Pediatric", "General", "Neurotology", "Facial Plastics")

# Calculate assortativity for each specialty of interest
for (specialty in specialties_of_interest) {
  calculate_assortativity_for_specialty(specialty)
}
```